// AUTO-GENERATED FROM prisma/schema.prisma
// DO NOT EDIT - This file is automatically generated when running 'bun prisma generate'
// Generated at: 2025-11-29T07:30:17.158Z

/**
 * Client-safe enum definitions extracted from Prisma schema
 * These can be safely imported in both server and client components
 */

export const UserRole = {
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
  BROKER: 'BROKER'
} as const;

export type UserRole = typeof UserRole[keyof typeof UserRole];

export const TenantType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY'
} as const;

export type TenantType = typeof TenantType[keyof typeof TenantType];

export const GuarantorType = {
  NONE: 'NONE',
  JOINT_OBLIGOR: 'JOINT_OBLIGOR',
  AVAL: 'AVAL',
  BOTH: 'BOTH'
} as const;

export type GuarantorType = typeof GuarantorType[keyof typeof GuarantorType];

export const PropertyType = {
  HOUSE: 'HOUSE',
  APARTMENT: 'APARTMENT',
  COMMERCIAL: 'COMMERCIAL',
  OFFICE: 'OFFICE',
  WAREHOUSE: 'WAREHOUSE',
  OTHER: 'OTHER'
} as const;

export type PropertyType = typeof PropertyType[keyof typeof PropertyType];

export const NationalityType = {
  MEXICAN: 'MEXICAN',
  FOREIGN: 'FOREIGN'
} as const;

export type NationalityType = typeof NationalityType[keyof typeof NationalityType];

export const PolicyStatus = {
  DRAFT: 'DRAFT',
  COLLECTING_INFO: 'COLLECTING_INFO',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  INVESTIGATION_REJECTED: 'INVESTIGATION_REJECTED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  CONTRACT_PENDING: 'CONTRACT_PENDING',
  CONTRACT_SIGNED: 'CONTRACT_SIGNED',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED'
} as const;

export type PolicyStatus = typeof PolicyStatus[keyof typeof PolicyStatus];

export const DocumentCategory = {
  IDENTIFICATION: 'IDENTIFICATION',
  INCOME_PROOF: 'INCOME_PROOF',
  ADDRESS_PROOF: 'ADDRESS_PROOF',
  BANK_STATEMENT: 'BANK_STATEMENT',
  PROPERTY_DEED: 'PROPERTY_DEED',
  TAX_RETURN: 'TAX_RETURN',
  EMPLOYMENT_LETTER: 'EMPLOYMENT_LETTER',
  PROPERTY_TAX_STATEMENT: 'PROPERTY_TAX_STATEMENT',
  MARRIAGE_CERTIFICATE: 'MARRIAGE_CERTIFICATE',
  COMPANY_CONSTITUTION: 'COMPANY_CONSTITUTION',
  LEGAL_POWERS: 'LEGAL_POWERS',
  TAX_STATUS_CERTIFICATE: 'TAX_STATUS_CERTIFICATE',
  CREDIT_REPORT: 'CREDIT_REPORT',
  PROPERTY_REGISTRY: 'PROPERTY_REGISTRY',
  PROPERTY_APPRAISAL: 'PROPERTY_APPRAISAL',
  PASSPORT: 'PASSPORT',
  IMMIGRATION_DOCUMENT: 'IMMIGRATION_DOCUMENT',
  UTILITY_BILL: 'UTILITY_BILL',
  PAYROLL_RECEIPT: 'PAYROLL_RECEIPT',
  OTHER: 'OTHER'
} as const;

export type DocumentCategory = typeof DocumentCategory[keyof typeof DocumentCategory];

export const InvestigationVerdict = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  HIGH_RISK: 'HIGH_RISK',
  CONDITIONAL: 'CONDITIONAL'
} as const;

export type InvestigationVerdict = typeof InvestigationVerdict[keyof typeof InvestigationVerdict];

export const RiskLevel = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  VERY_HIGH: 'VERY_HIGH'
} as const;

export type RiskLevel = typeof RiskLevel[keyof typeof RiskLevel];

export const PaymentStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIAL: 'PARTIAL'
} as const;

export type PaymentStatus = typeof PaymentStatus[keyof typeof PaymentStatus];

export const PaymentMethod = {
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CASH: 'CASH',
  STRIPE: 'STRIPE',
  MANUAL: 'MANUAL'
} as const;

export type PaymentMethod = typeof PaymentMethod[keyof typeof PaymentMethod];

export const PaymentType = {
  INVESTIGATION_FEE: 'INVESTIGATION_FEE',
  POLICY_PREMIUM: 'POLICY_PREMIUM',
  PARTIAL_PAYMENT: 'PARTIAL_PAYMENT',
  INCIDENT_PAYMENT: 'INCIDENT_PAYMENT',
  REFUND: 'REFUND'
} as const;

export type PaymentType = typeof PaymentType[keyof typeof PaymentType];

export const PayerType = {
  TENANT: 'TENANT',
  LANDLORD: 'LANDLORD',
  JOINT_OBLIGOR: 'JOINT_OBLIGOR',
  AVAL: 'AVAL',
  COMPANY: 'COMPANY'
} as const;

export type PayerType = typeof PayerType[keyof typeof PayerType];

export const ReporterType = {
  TENANT: 'TENANT',
  LANDLORD: 'LANDLORD',
  JOINT_OBLIGOR: 'JOINT_OBLIGOR',
  AVAL: 'AVAL',
  STAFF: 'STAFF',
  OTHER: 'OTHER'
} as const;

export type ReporterType = typeof ReporterType[keyof typeof ReporterType];

export const IncidentStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  ESCALATED: 'ESCALATED'
} as const;

export type IncidentStatus = typeof IncidentStatus[keyof typeof IncidentStatus];

export const ActorVerificationStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_REVIEW: 'IN_REVIEW'
} as const;

export type ActorVerificationStatus = typeof ActorVerificationStatus[keyof typeof ActorVerificationStatus];

export const ValidationStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_REVIEW: 'IN_REVIEW'
} as const;

export type ValidationStatus = typeof ValidationStatus[keyof typeof ValidationStatus];

export const RulesType = {
  CONDOMINIOS: 'CONDOMINIOS',
  CONDOMINOS: 'CONDOMINOS',
  COLONOS: 'COLONOS'
} as const;

export type RulesType = typeof RulesType[keyof typeof RulesType];

// Utility function to get enum values as array
export function getEnumValues<T extends Record<string, string>>(enumObj: T): T[keyof T][] {
  return Object.values(enumObj) as T[keyof T][];
}

/**
 * Usage examples:
 * 
 * // Import in client component
 * import { UserRole, PolicyStatus } from "@/lib/enums";
 * 
 * // Use in comparisons
 * if (user.role === UserRole.ADMIN) { ... }
 * 
 * // Get all values for a select
 * const roleOptions = getEnumValues(UserRole);
 */