// AUTO-GENERATED FROM prisma/schema.prisma
// DO NOT EDIT - This file is automatically generated when running 'bun prisma generate'
// Generated at: 2025-11-29T23:54:42.767Z

/**
 * Client-safe enum definitions extracted from Prisma schema
 * These can be safely imported in both server and client components
 */

// Utility function to get enum values as array
export function getEnumValues<T extends Record<string, string>>(enumObj: T): T[keyof T][] {
  return Object.values(enumObj) as T[keyof T][];
}

/**
 * Usage examples:
 * 
 * // Import in client component
 * import { UserRole, PolicyStatus } from "@/lib/enums";
 * 
 * // Use in comparisons
 * if (user.role === UserRole.ADMIN) { ... }
 * 
 * // Get all values for a select
 * const roleOptions = getEnumValues(UserRole);
 */